#install with conda env create -f environment.yml
#conda activate my-env
name: my-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - statsmodels
  - sqlalchemy
  - pymysql
  - requests
  - ipython
  - pip
  - pip:
      - ipython-sql
      - mysql-connector-python
      
